CREATE TABLE conversation_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_member_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversation(id),

    CONSTRAINT fk_member_user
        FOREIGN KEY (user_id) REFERENCES users(id),

    CONSTRAINT uq_conversation_user
        UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_conversation_member_user
    ON conversation_member (user_id);