CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value VARCHAR(255) NOT NULL UNIQUE,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

    CONSTRAINT fk_member_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversation(id),

    CONSTRAINT fk_member_user
        FOREIGN KEY (user_id) REFERENCES users(id),

    CONSTRAINT uq_conversation_user
        UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_message_conversation_created
    ON message (conversation_id, created_at DESC, id DESC);