name: Tests Front/Back

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  test-frontend:
    name: Angular Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Angular tests
        run: npm test -- --watch=false

  test-backend:
    name: Spring Boot Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: authentication_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '26'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test